### ISSUE TITLE
[FEAT] Default `tiff_folder_key` parameter for ImportTiffPipeline

### ISSUE THREAD

**Issue by mlubej** [sentinel-hub/eo-grow#160]
Usually we treat the `input-data` folder as the default when running some pipelines, where this is the location of input data to be used in the specific pipeline. 

Usually it was not the case that one had to provide specific folder keys for `input-data`, so perhaps I would suggest to use the `input-data` location as a default in cases where the `tiff_folder_key` parameter is not provided when running the  `ImportTiffPipeline`. This would make the `tiff_folder_key` parameter optional.

IMHO since the input-data is always there and is just one, there is no need to explicitly provide it as a folder key.

**Comment by zigaLuksic** [comment]
Agreed. Prepare a MR or remind me if i forget :)
