### ISSUE TITLE
[BUG] further issues with batch_to_eopatch pipeline

### ISSUE THREAD

**Issue by mlubej** [sentinel-hub/eo-grow#17]
**Describe the bug**

Seems like even with the changes from [#12](https://github.com/sentinel-hub/eo-grow/pull/15) I still get issues if `boundless=True` in the `src.read` part of the `ImportFromTiffTask`. I tried setting `boundless` to `False` and then it works. This makes sense if `eopatch` is `None`, but not necessarily if it exists before, so this needs to be tested.

**To Reproduce**

1. Run batch download pipeline
2. Run batch to eopatch pipeline with changes from [#13 ](https://github.com/sentinel-hub/eo-grow/pull/15)

**Comment by AleksMat** [comment]
@mlubej is this still an issue even after the fix in https://github.com/sentinel-hub/eo-learn/pull/388? (The fix has already been released in `eo-learn` `1.0.1`.)
