### ISSUE TITLE
[FEAT] Batch download pipeline doesn't have the option to set a maxcc filter

### ISSUE THREAD

**Issue by mlubej** [sentinel-hub/eo-grow#35]
**What is the problem? Please describe.**

The batch download pipeline doesn't have the option to set a `maxcc` filter. This could allow the user to set a filter on the number of tiles to be considered and reduce the size of the downloaded.

It's possible that I'm missing some fact and that this was perhaps intentional.

**Comment by AleksMat** [comment]
Added in https://github.com/sentinel-hub/eo-grow/pull/38. It will be released in `eo-grow` `1.1.0`.
